name: Deployment Pipeline

on:
  push:
    branches:
      - master
      
jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - run: ls -a
      - name: Linting
        run: npm run lint